UHM-6058: Migration Failing on Order migration
PIH/openmrs-config-zl pull request #171
Opened 2022-01-05 17:38 UTC by mogoodrich

2022-01-05 17:39 UTC, mogoodrich commented on configuration/pih/drugs/drugs.csv
> +0f3b5757-30ab-46cd-8e59-02cb88ae3e1f,,"Ethambutol + Isoniazide 400/150 mg - 550 milligram Tablet",PIH:1108,
Awaiting OpenBoxes code, @lnball is it okay to leave blank for now?
Also, please tweak name as you see fit

2022-01-06 16:15 UTC, lnball commented
Why is my comment "pending"?  I assume you can't see my comment @mogoodrich ?

2022-01-06 16:16 UTC, lnball commented
This was my comment on the code @mogoodrich 

* Change the name to "Ethambutol (E) 400mg + Isoniazide (H) 150mg, tablet".
* Emailed the ZL pharmacist (Johnny).
* Added RxNorm, CIEL, and SNOMED mappings to the concept

Does the config code need the missing navcode @mogoodrich ?

2022-01-06 16:18 UTC, lnball requested changes

2022-01-06 21:49 UTC, mogoodrich commented
Thanks @lnball ... I tweaked the name as you suggested and confirmed that the OB code is not needed, merging...

2022-01-06 21:49 UTC, merged