HIV Ped:- Secondhand smoke, cholera and Chikungunya
PIH/openmrs-config-zl pull request #19
Opened 2020-09-09 20:33 UTC by jmbabazi

2020-09-09 21:11 UTC, lnball requested changes

2020-09-09 21:11 UTC, lnball commented on configuration/pih/htmlforms/hiv/zl/section-hiv-history.xml
> +            <!-- Secondary smoke -->
On the paper, this question is at the end of the section (not with smoking).  For now, we can keep it with smoking, but the order will be different from paper.  The Pediatrics form is also missing drugs.  I think that we should keep that for all ages.

Adult:  Smoking, Alcohol, Drugs
Pediatrics:  Smoking, Alcohol, Second-hand smoke

2020-09-10 13:57 UTC, jmbabazi commented on configuration/pih/htmlforms/hiv/zl/section-hiv-history.xml
> +                <pastMedicalHistoryCheckbox concept="CIEl:120742"
Thanks @lnball , pushed the fix

2020-09-10 14:29 UTC, lnball approved these changes

2020-09-10 14:29 UTC, merged