HAI-668:Add DTG 5mg to the list of drugs
PIH/openmrs-config-zl pull request #203
Opened 2022-05-19 14:54 UTC by louidorjp

Please review this PR @lnball @rjacques89 @mogoodrich

2022-05-19 15:09 UTC, lnball commented on configuration/pih/htmlforms/hiv/hiv-dispensing.xml
> +                                DTG 5mg,
@louidorjp Looks good, but I would suggest changing the order so it's 50, 10, 5mg (instead of 50, 5, 10) and same order as the ARV #2

2022-05-19 15:10 UTC, lnball requested changes
Small change but looks good and nice improvement.

2022-05-20 15:16 UTC, louidorjp commented
@lnball list of drugs ARV #1 updated

2022-05-20 21:35 UTC, merged

2022-05-20 21:35 UTC, lnball commented
Looks good.  Thanks @louidorjp